### ISSUE TITLE
Undefined Function Error calling NoteApp.Notes.NoteServer.start_link

### ISSUE THREAD

**Issue by 2FO** [abulsayyad123/elixir-note-taking-app#1]
Hi, 

Your tutorial looks like a very good intro to LiveView and GenServers, thanks for taking the time to put it together.

I've only gotten as far as creating the initial module "note_server.ex", but I'm running into the following issue:

Attempting to get the pid in iex:

```{:ok, pid} = NoteApp.Notes.NoteServer.start_link()```

Returns: 
``` 
 **(UndefinedFunctionError) function NoteApp.Notes.NoteServer.start_link/0 is undefined or private. Did you mean one of:

      * start_link/1

    (note_app 0.1.0) NoteApp.Notes.NoteServer.start_link()
```
Here's my code from "note_app/lib/note_app/notes/note_server.ex"
```
defmodule NoteApp.Notes.NoteServer do
  use GenServer

  def start_link(_args) do
    GenServer.start_link(__MODULE__, [], name: __MODULE__)
  end

  def init(notes) do
    {:ok, notes}
  end
end
```

**Comment by abulsayyad123** [comment]
Hello @2FO, thanks for reading the blog and trying it out. I'll suggest you try this
```
def start_link() do
   GenServer.start_link(__MODULE__, [])
end
```
Since initially, we are calling it out by ourselves from iex shell we don't need the third parameter. 
Try it out and let me know if you are stuck in something. I'll try to answer you as early as possible. Also, if possible follow the order of the commits that will help you developing.

**Comment by 2FO** [comment]
Thanks for the quick reply.  Removing the third parameter didn't work for me.  I did get it to work by passing "nil" as the argument. 

``` {:ok, pid} = NoteApp.Notes.NoteServer.start_link(nil)```
